### ISSUE TITLE
Roadmap to live

### ISSUE THREAD

**Issue by taddeimania** [taddeimania/lctva#2]
So the current status is alpha but signups are obviously not closed and access is completely open to any streamer on livecoding.tv but there are a few things i'd like to have accomplished before I consider this site anything but "beta".

This could also act as an opportunity for other community members to take ownership of a part of the site or to jump in on a feature someone else is working on.  If you're interested in taking part in the development let me know in an email or post in this thread and we'll find something for you to do :smile:.
### Design / UX
- [x] Actual dashboard appearance.  Something like [this.](http://themeforest.net/item/materialize-material-design-admin-template/11446068) I am open to purchasing templates to adapt to the site.
- [x] ~~Front end as a single page app? I know Ember best but if someone wants to work on turning the graph widgets into some react components i'd be good with that.~~ Not doing
### Backend Async Tasks
- [ ] Daily / Weekly / Monthly digest emails compiling a user's stats, peak viewership, etc.
### Misc Backend
- [x] "Login with livecoding.tv", Take away user creation, allow users to create an account with only authorizing from livecoding.tv. (Good task for someone who wants to learn more about oauth2)
- [x] Collect all the data. Collect data on all streamers of livecoding.tv rather than just users who have authorized. Allowing new users to see their historic data.
- [x] Localize tzinfo for all users
- [ ] Daily and Monthly Leaderboards https://github.com/taddeimania/lctva/issues/13
- [ ] Improve test coverage
### External (good luck)
- [x] Raise livecoding.tv throttling limits. https://github.com/taddeimania/lctva/issues/4

I will continually add or remove things from this list as requirements change.

**Comment by taddeimania** [comment]
formal invite for @Cheyans and @pingjocky to find something that interests them in this thread ;)
